### PR TITLE
Modified URLs to use https rather than http

### PR DESCRIPTION
**Pull request by tkeuning**

### CODE REVIEW

**Comment by tkeuning** [comment]
This builds on the SSL fix in https://github.com/plexinc-plugins/PBSKids.bundle/pull/12 by changing the URLs in use in the plugin from http to https

**Comment by mddepew** [comment]
I haven't had the chance to pull and test the change, but in theory it shouldn't be a problem to switch those URLs to https. It should be noted that the only way to make SSL work was to use older ciphers and limited certificate validation. The implementation in the current code is NOT secure. I don't think that's a problem for the type of traffic we have here. It's not like clients are sending financial information.

**Comment by tkeuning** [comment]
Agreed about the security -- this is not ideal, but in light of the switch PBS kids seems to have made to enforce https, and the SSL capabilities in Plex, it seems to be a reasonable shortcut.

As for testing -- in my local testing, I was unable to get results with the state of the master code as-is; changing to https made it work for me.  Would it be helpful if those test results (screenshots or logs) were attached to the PR?

**Comment by mddepew** [comment]
That's interesting. I'm running the master code on my system and it seems to be working. If you can post log files showing what errors you're getting with the current master code that would be helpful. That's mostly out of curiosity as to why the master code isn't working for you. I would recommend that the pull request be accepted as is though. I don't have write authority on this repo, so @sander1 will have to be the one to make the merge.

**Comment by tkeuning** [comment]
And having gone back to review what I saw so I could add logs to the PR, I realize that my initial problems have disappeared... I must have been using an older code base unwittingly.

I'm going to close this my initial assessment of the need for change was unfounded.

Thanks!

**Pull request closed without merging**
