### PR TITLE
Update plugin to handle site redesign

### PR DESCRIPTION
**Pull request by jjlawren**
Updated the plugin with minimal changes to simply get it working again, hopefully solving https://github.com/plexinc-plugins/PBSKids.bundle/issues/5. The only (obvious) problem I can find is that thumbnails on the video pages themselves don't seem to load properly.

### CODE REVIEW

**Comment by tdugan** [comment]
Hey, does this work?  I try to select the widget in plex and get "the server encountered an error when trying to respond to the request".... Assume this is the same plugin I'd get directly from plex?

 Thanks in advance for a reply...

**Comment by sander1** [comment]
It works again after today's update (319dff5368e64ac350317ef412b6393cad21c141). The update has been released through the Plex Channel Directory. Your Plex Media Server will download the update automatically.

**Comment by tdugan** [comment]
Thanks, works like a charm :)

**Comment by sander1** [comment]
And now the URL has changed again... To... Something else, need to figure that out.

**Comment by sander1** [comment]
Fixed again (1355ef2dc653ffc8682124e142bba5a1f8094eb3)!

**Pull request merged**
